# This file was generated by GoReleaser. DO NOT EDIT.
cask "leo" do
  version "0.18.0"

  on_macos do
    on_intel do
      sha256 "74792516b3a3a118324644e0a8fdaaca56d4a67e15b62f77625191bcb13858c3"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/blackpaw-studio/leo/releases/download"
    end
    on_arm do
      sha256 "f09c2d28d98f0b3d72fbd12774ae6c5dbd7b0ea8cb5a5d6f573fb0cedfb75949"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/blackpaw-studio/leo/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "abe150c22bb8e93b69485139b679999f0c11d5ce3eed1f9dccf2abcfeaa6f089"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/blackpaw-studio/leo/releases/download"
    end
    on_arm do
      sha256 "ef44e5bedcef9b6b65d839f463b846b8eaa6e503779baa4181ec0435d960323e"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/blackpaw-studio/leo/releases/download"
    end
  end

  name "leo"
  desc "Supervise persistent Claude Code agents with scheduling and channel plugins"
  homepage "https://github.com/blackpaw-studio/leo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "leo"

  # No zap stanza required

  caveats <<~EOS
    leo requires the `claude` CLI at runtime. Install it from:
      https://docs.claude.com/claude-code

    On first run, configure leo with:
      leo setup
  EOS
end
