# This file was generated by GoReleaser. DO NOT EDIT.
cask "leo" do
  version "0.43.0"

  on_macos do
    on_arm do
      sha256 "2059c58dd562ec5557642cbe9d51ad6c4e6282da27d05bc40927394f107bd75e"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b0cfb85904a2b9e94a23d6f0da208c00ddcb7d0bf516be0d19b770bee0b1c65"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "694c9e91ca08360e70c0379eda6f0bc059124f998558545ac0e2538740ab4ffd"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a27e0c73b87e0e12fe807eabbb41db5482f56cdf493d8f7013fee7194522ba95"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "leo"
  desc "Supervise persistent Claude Code agents with scheduling and channel plugins"
  homepage "https://github.com/blackpaw-studio/leo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "leo"

  # No zap stanza required

  caveats <<~EOS
    leo requires the `claude` CLI at runtime. Install it from:
      https://docs.claude.com/claude-code

    On first run, configure leo with:
      leo setup
  EOS
end
