# This file was generated by GoReleaser. DO NOT EDIT.
cask "leo" do
  version "0.25.1"

  on_macos do
    on_arm do
      sha256 "969d36f1580bd446af2e4339bd1bcc83f323bae1fc99913ab5d392eb6e09ef2b"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ed6c900a90bb1754c287a4a22fe3d0aeb1e780acda473ce89895442f0526c48"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fbeacc70406e9405fb0344b2d43903cd5a71dae01a5b7223e3bd37d09962ac83"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f52481367f80942ed7da448c3b1fb6b6910dbb982278bd457c0a82f820d5527c"
      url "https://github.com/blackpaw-studio/leo/releases/download/v#{version}/leo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "leo"
  desc "Supervise persistent Claude Code agents with scheduling and channel plugins"
  homepage "https://github.com/blackpaw-studio/leo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "leo"

  # No zap stanza required

  caveats <<~EOS
    leo requires the `claude` CLI at runtime. Install it from:
      https://docs.claude.com/claude-code

    On first run, configure leo with:
      leo setup
  EOS
end
