# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leo < Formula
  desc "Supervise persistent Claude Code agents with scheduling and channel plugins"
  homepage "https://github.com/blackpaw-studio/leo"
  version "0.2.2"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackpaw-studio/leo/releases/download/v0.2.2/leo_0.2.2_darwin_amd64.tar.gz"
      sha256 "30531a0cc20d070df20f42464efb66c5111eb3b61a9aeea21a6cf0de2bfa3321"

      define_method(:install) do
        bin.install "leo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackpaw-studio/leo/releases/download/v0.2.2/leo_0.2.2_darwin_arm64.tar.gz"
      sha256 "071b3da210281a602b4cb53fbc22c2173bac34cab669ea98af6d86968ac39369"

      define_method(:install) do
        bin.install "leo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackpaw-studio/leo/releases/download/v0.2.2/leo_0.2.2_linux_amd64.tar.gz"
      sha256 "37645b904bc3f3c7600f8e7df545efbccdcd7d2a33986405cf3e24f2a81e3437"
      define_method(:install) do
        bin.install "leo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackpaw-studio/leo/releases/download/v0.2.2/leo_0.2.2_linux_arm64.tar.gz"
      sha256 "7ee13d6f4007226bfaa17c77c8f2f5e9658f4e6aed5ed91055b57dff872f1d73"
      define_method(:install) do
        bin.install "leo"
      end
    end
  end

  def caveats
    <<~EOS
      leo requires the `claude` CLI at runtime. Install it from:
        https://docs.claude.com/claude-code

      On first run, configure leo with:
        leo setup
    EOS
  end

  test do
    assert_match "leo #{version}", shell_output("#{bin}/leo version")
  end
end
